"""
Script to generate automatically the configuration file for postgres
"""
import argparse
import multiprocessing
import psutil

parser = argparse.ArgumentParser(
    description='Generates automatically postgres configuration.')
parser.add_argument('--ram_factor', action="store", type=float, default=0.75)
parser.add_argument('--cpu_factor', action="store", type=float, default=1.0)
args = parser.parse_args()
total_ram_megabytes = int(psutil.virtual_memory().total / (1024 * 1024))
available_ram_megabytes = int(args.ram_factor * total_ram_megabytes)
cpu_cores = multiprocessing.cpu_count()
available_cpu_cores = int(args.cpu_factor * cpu_cores)


def clamp(value, target_format, min_value=None, max_value=None):
    """
    Clamps a value inside a range
    (defined by an optional min_value and max_value)
    and converts the result to a target format.
    """
    if min_value is not None:
        value = max(value, min_value)
    if max_value is not None:
        value = min(value, max_value)
    return target_format(value)


print ("""# Autogenerated file from pg_autoconf
# Based on https://pgtune.leopard.in.ua/
# DB Version: 10
# OS Type: linux
# DB Type: mixed
# Total Memory (RAM): {total_ram_megabytes}MB
# Available RAM for postgres: {available_ram_megabytes}MB ({args_ram_factor})
# CPUs num: {cpu_cores}
# Available CPUs num: {available_cpu_cores} ({args_cpu_factor})
# Data Storage: ssdmax_connections = 100
shared_buffers = {shared_buffers}MB
effective_cache_size = {effective_cache_size}MB
maintenance_work_mem = {maintenance_work_mem}MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 5242kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = {available_cpu_cores}
max_parallel_workers_per_gather = {max_parallel_workers_per_gather}
max_parallel_workers = {available_cpu_cores}listen_addresses = '*'
log_timezone = 'UTC'datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'en_US.utf8'			# locale for system error message
lc_monetary = 'en_US.utf8'			# locale for monetary formatting
lc_numeric = 'en_US.utf8'			# locale for number formatting
lc_time = 'en_US.utf8'				# locale for time formatting# default configuration for text search
default_text_search_config = 'pg_catalog.english'
""".format(
    total_ram_megabytes=total_ram_megabytes,
    available_ram_megabytes=available_ram_megabytes,
    args_ram_factor=args.ram_factor,
    cpu_cores=cpu_cores,
    available_cpu_cores=available_cpu_cores,
    args_cpu_factor=args.cpu_factor,
    shared_buffers=clamp(0.25 * available_ram_megabytes, int),
    effective_cache_size=clamp(0.75 * available_ram_megabytes, int),
    maintenance_work_mem=clamp(0.02 * available_ram_megabytes, int, min_value=64),
    max_parallel_workers_per_gather= clamp(0.5 * available_cpu_cores, int, min_value=1),
))

